# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateCurveWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(172, 186)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.create_curve_layout = QtWidgets.QHBoxLayout()
        self.create_curve_layout.setObjectName("create_curve_layout")
        self.verticalLayout_point1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_point1.setObjectName("verticalLayout_point1")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.input_x = QtWidgets.QLineEdit(Form)
        self.input_x.setObjectName("input_x")
        self.horizontalLayout.addWidget(self.input_x)
        self.verticalLayout_point1.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.input_y = QtWidgets.QLineEdit(Form)
        self.input_y.setObjectName("input_y")
        self.horizontalLayout_2.addWidget(self.input_y)
        self.verticalLayout_point1.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.input_z = QtWidgets.QLineEdit(Form)
        self.input_z.setObjectName("input_z")
        self.horizontalLayout_3.addWidget(self.input_z)
        self.verticalLayout_point1.addLayout(self.horizontalLayout_3)
        self.create_curve_layout.addLayout(self.verticalLayout_point1)
        self.verticalLayout.addLayout(self.create_curve_layout)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.applyButton = QtWidgets.QPushButton(Form)
        self.applyButton.setObjectName("applyButton")
        self.verticalLayout.addWidget(self.applyButton)
        self.cancelButton = QtWidgets.QPushButton(Form)
        self.cancelButton.setObjectName("cancelButton")
        self.verticalLayout.addWidget(self.cancelButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Curve:"))
        self.label.setText(_translate("Form", "x(t) ="))
        self.label_2.setText(_translate("Form", "y(t) ="))
        self.label_3.setText(_translate("Form", "z(t) ="))
        self.applyButton.setText(_translate("Form", "Apply"))
        self.cancelButton.setText(_translate("Form", "Cancel"))
