# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ObjectWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(154, 38)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_name = QtWidgets.QLabel(Form)
        self.label_name.setObjectName("label_name")
        self.horizontalLayout.addWidget(self.label_name)
        self.functionsBox = QtWidgets.QComboBox(Form)
        self.functionsBox.setObjectName("functionsBox")
        self.functionsBox.addItem("")
        self.functionsBox.addItem("")
        self.functionsBox.addItem("")
        self.functionsBox.addItem("")
        self.horizontalLayout.addWidget(self.functionsBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_name.setText(_translate("Form", "ObjectName"))
        self.functionsBox.setItemText(0, _translate("Form", "Rename "))
        self.functionsBox.setItemText(1, _translate("Form", "Clone "))
        self.functionsBox.setItemText(2, _translate("Form", "Translate"))
        self.functionsBox.setItemText(3, _translate("Form", "Delete"))
